name: Deploy to Azure Web App

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  AZURE_WEBAPP_NAME: shared-learning-app
  AZURE_WEBAPP_PACKAGE_PATH: "."

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build and prepare for manual deployment
        run: |
          # Find the JAR file
          JAR_FILE=$(find target -name "*.jar" | head -1)
          echo "Found JAR file: $JAR_FILE"

          # Create deployment info
          echo "## Deployment Instructions" >> deployment-info.md
          echo "1. Go to Kudu Console: https://shared-learning-app-gfayfce4a2e6b8bd.scm.eastasia-01.azurewebsites.net" >> deployment-info.md
          echo "2. Navigate to Debug Console → Bash" >> deployment-info.md
          echo "3. Run: cd /home/site/wwwroot" >> deployment-info.md
          echo "4. Upload the JAR file: $JAR_FILE" >> deployment-info.md
          echo "5. Rename to: app.jar" >> deployment-info.md
          echo "6. Configure Startup Command in Azure Portal" >> deployment-info.md

          echo "Manual deployment required. See deployment-info.md for instructions."

      - name: Health check
        run: |
          echo "Waiting for deployment to complete..."
          sleep 60
          curl -f https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/health/simple || echo "Health check failed"
