name: Deploy to Azure Web App

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  AZURE_WEBAPP_NAME: shared-learning-app
  AZURE_WEBAPP_PACKAGE_PATH: "."

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Deploy to Azure Web App using FTPS
        run: |
          # Find the JAR file
          JAR_FILE=$(find target -name "*.jar" | head -1)
          echo "Found JAR file: $JAR_FILE"

          # Install lftp for FTPS upload
          sudo apt-get update && sudo apt-get install -y lftp

          # Deploy using FTPS
          echo "Deploying to Azure Web App via FTPS..."

          # Create lftp script
          cat > deploy.lftp << EOF
          set ssl:verify-certificate no
          open ftps://waws-prod-hk1-057.ftp.azurewebsites.windows.net
          user ${{ secrets.AZURE_FTPS_USERNAME }} ${{ secrets.AZURE_FTPS_PASSWORD }}
          cd /site/wwwroot
          put $JAR_FILE app.jar
          bye
          EOF

          # Execute lftp script
          lftp -f deploy.lftp

          echo "Deployment completed!"

      - name: Health check
        run: |
          echo "Waiting for deployment to complete..."
          sleep 60
          curl -f https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/health/simple || echo "Health check failed"
