name: Deploy to Azure Web App

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  AZURE_WEBAPP_NAME: shared-learning-app
  AZURE_WEBAPP_PACKAGE_PATH: "."

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Deploy to Azure Web App using Kudu API
        run: |
          # Find the JAR file
          JAR_FILE=$(find target -name "*.jar" | head -1)
          echo "Found JAR file: $JAR_FILE"

          # Create deployment package
          mkdir -p deploy
          cp "$JAR_FILE" deploy/app.jar
          cd deploy
          zip -r ../deploy.zip .
          cd ..

          # Deploy using Kudu REST API with deployment credentials
          echo "Deploying to Azure Web App..."
          curl -X POST \
            -H "Content-Type: application/zip" \
            -H "Authorization: Basic $(echo -n '${{ secrets.AZURE_DEPLOY_USERNAME }}:${{ secrets.AZURE_DEPLOY_PASSWORD }}' | base64)" \
            --data-binary @deploy.zip \
            "https://${{ env.AZURE_WEBAPP_NAME }}.scm.azurewebsites.net/api/zipdeploy"

          echo "Deployment completed!"

      - name: Health check
        run: |
          echo "Waiting for deployment to complete..."
          sleep 60
          curl -f https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/health/simple || echo "Health check failed"
