name: Deploy to Azure Web App

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  AZURE_WEBAPP_NAME: shared-learning-app
  AZURE_WEBAPP_PACKAGE_PATH: "."

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Deploy to Azure Web App using FTP
        run: |
          # Install curl if not available
          sudo apt-get update && sudo apt-get install -y curl

          # Upload JAR file using FTP
          echo "Uploading JAR file to Azure Web App..."

          # Find the JAR file
          JAR_FILE=$(find target -name "*.jar" | head -1)
          echo "Found JAR file: $JAR_FILE"

          # Create a simple deployment script
          cat > deploy.sh << 'EOF'
          #!/bin/bash
          # Simple FTP upload script
          HOST="waws-prod-hk1-057.ftp.azurewebsites.windows.net"
          USER="${{ secrets.AZURE_WEBAPP_USERNAME }}"
          PASS="${{ secrets.AZURE_WEBAPP_PASSWORD }}"
          FILE="$1"

          echo "Uploading $FILE to $HOST..."

          # Use curl for FTP upload
          curl -T "$FILE" "ftps://$HOST/site/wwwroot/app.jar" \
            --user "$USER:$PASS" \
            --ftp-create-dirs \
            --ftp-ssl \
            --ftp-ssl-reqd

          if [ $? -eq 0 ]; then
            echo "Upload successful!"
          else
            echo "Upload failed!"
            exit 1
          fi
          EOF

          chmod +x deploy.sh
          ./deploy.sh "$JAR_FILE"

      - name: Health check
        run: |
          echo "Waiting for deployment to complete..."
          sleep 60
          curl -f https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/health/simple || echo "Health check failed"
