name: Build and Prepare for Deployment

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  AZURE_WEBAPP_NAME: shared-learning-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Find JAR file
        id: find-jar
        run: |
          JAR_FILE=$(find target -name "*.jar" | head -1)
          echo "Found JAR file: $JAR_FILE"
          echo "jar-path=$JAR_FILE" >> $GITHUB_OUTPUT

          # Copy JAR to root for easier access
          cp "$JAR_FILE" app.jar

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: app.jar

      - name: Create deployment instructions
        run: |
          echo "## 🚀 Deployment Instructions" > deployment-info.md
          echo "" >> deployment-info.md
          echo "### 1. Download JAR file" >> deployment-info.md
          echo "- Go to Actions tab in this repository" >> deployment-info.md
          echo "- Click on the latest workflow run" >> deployment-info.md
          echo "- Download the 'app-jar' artifact" >> deployment-info.md
          echo "" >> deployment-info.md
          echo "### 2. Deploy to Azure" >> deployment-info.md
          echo "- Go to Kudu Console: https://${{ env.AZURE_WEBAPP_NAME }}-gfayfce4a2e6b8bd.scm.eastasia-01.azurewebsites.net" >> deployment-info.md
          echo "- Navigate to Debug Console → Bash" >> deployment-info.md
          echo "- Run: cd /home/site/wwwroot" >> deployment-info.md
          echo "- Upload the downloaded JAR file" >> deployment-info.md
          echo "- Rename to: app.jar" >> deployment-info.md
          echo "- Set startup command in Azure Portal: java -jar app.jar" >> deployment-info.md
          echo "" >> deployment-info.md
          echo "### 3. Restart App Service" >> deployment-info.md
          echo "- Go to Azure Portal → App Service → Restart" >> deployment-info.md

          echo "✅ Build completed! Check deployment-info.md for instructions."
